# Generated by Django 6.0.5 on 2026-07-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridge', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.RemoveField(
            model_name='fooddonation',
            name='donor',
        ),
        migrations.DeleteModel(
            name='NGO',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
        migrations.DeleteModel(
            name='FoodDonation',
        ),
    ]
