# Generated by Django 6.0.5 on 2026-08-13 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteers', '0004_pickup_workspace_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NGOPaymentConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_account_id', models.CharField(max_length=100, unique=True)),
                ('access_token_encrypted', models.TextField()),
                ('refresh_token_encrypted', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ngo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paise', models.PositiveIntegerField(default=50000)),
                ('status', models.CharField(choices=[('AWAITING_NGO_CONFIRMATION', 'Awaiting NGO confirmation'), ('AWAITING_NGO_PAYMENT', 'Awaiting NGO payment'), ('PAYMENT_PENDING', 'Payment pending'), ('PAYMENT_CAPTURED', 'Payment captured'), ('PAYMENT_FAILED', 'Payment failed'), ('PAYOUT_READY', 'Payout ready'), ('PAYOUT_PROCESSING', 'Payout processing'), ('PAYOUT_PROCESSED', 'Payout processed'), ('PAYOUT_FAILED', 'Payout failed')], default='AWAITING_NGO_CONFIRMATION', max_length=32)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('razorpay_payout_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('razorpay_contact_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_fund_account_id', models.CharField(blank=True, max_length=100)),
                ('payout_idempotency_key', models.CharField(blank=True, max_length=64, unique=True)),
                ('ngo_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payout_released_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='volunteer_payments', to=settings.AUTH_USER_MODEL)),
                ('pickup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_payment', to='volunteers.pickup')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerPayoutProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('UPI', 'UPI'), ('BANK', 'Bank account')], max_length=10)),
                ('upi_id_encrypted', models.TextField(blank=True)),
                ('account_holder_encrypted', models.TextField(blank=True)),
                ('account_number_encrypted', models.TextField(blank=True)),
                ('ifsc_encrypted', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
