# Generated by Django 6.0.5 on 2026-07-30 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='service_area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='transport_mode',
            field=models.CharField(choices=[('WALKING', 'Walking'), ('BICYCLE', 'Bicycle'), ('MOTORCYCLE', 'Motorcycle'), ('CAR', 'Car'), ('OTHER', 'Other')], default='WALKING', max_length=20),
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=200)),
                ('donor_phone', models.CharField(max_length=15)),
                ('pickup_address', models.TextField()),
                ('pickup_city', models.CharField(max_length=100)),
                ('food_description', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=100)),
                ('pickup_window_start', models.DateTimeField()),
                ('pickup_window_end', models.DateTimeField()),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLAIMED', 'Claimed'), ('COLLECTED', 'Collected'), ('DELIVERED', 'Delivered')], db_index=True, default='OPEN', max_length=20)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('recipient_address', models.TextField(blank=True)),
                ('handoff_notes', models.TextField(blank=True)),
                ('delivery_photo', models.ImageField(blank=True, upload_to='delivery_proofs/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pickup_window_start', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('CLAIMED', 'COLLECTED'))), fields=('assigned_volunteer',), name='one_active_pickup_per_volunteer')],
            },
        ),
    ]
