# Generated by Django 6.0.5 on 2026-08-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0005_gps_location_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='delivery_photo',
            field=models.ImageField(blank=True, upload_to='private/delivery_proofs/%Y/%m/'),
        ),
    ]
