# Generated by Django 6.0.5 on 2026-07-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ngos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ngoprofile",
            name="address",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
