# Generated by Django 6.0.5 on 2026-08-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngos', '0003_ngoprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoprofile',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=16),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
