# Generated by Django 6.0.5 on 2026-07-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('DONOR', 'Donor'), ('VOLUNTEER', 'Volunteer'), ('NGO', 'NGO')], max_length=20),
        ),
    ]
