# Generated by Django 6.0.5 on 2026-08-13 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_active_and_ngo_status_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='receiving_ngo',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'NGO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('NGO_ACCEPTED', 'NGO accepted'), ('VOLUNTEER_CLAIMED', 'Volunteer claimed'), ('IN_TRANSIT', 'In transit'), ('AWAITING_NGO_CONFIRMATION', 'Awaiting NGO confirmation'), ('DELIVERED', 'Delivered'), ('NGO_MANAGED', 'NGO managed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='AVAILABLE', max_length=32),
        ),
    ]
