# Generated by Django 6.0.5 on 2026-08-13 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donation_receiving_ngo_alter_donation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='food_photo_closeup',
            field=models.ImageField(blank=True, upload_to='donation_photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='donation',
            name='food_photo_label',
            field=models.ImageField(blank=True, upload_to='donation_photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='donation',
            name='food_photo_overview',
            field=models.ImageField(blank=True, upload_to='donation_photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_unpackaged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='verification_confidence',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='verification_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='verification_provider',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='donation',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('HUMAN_REVIEW', 'Awaiting human review')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='verification_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='visible_risk_flags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
