# Generated by Django 6.0.5 on 2026-08-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_donation_pickup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='food_photo_closeup',
            field=models.ImageField(blank=True, upload_to='private/donation_photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='food_photo_label',
            field=models.ImageField(blank=True, upload_to='private/donation_photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='food_photo_overview',
            field=models.ImageField(blank=True, upload_to='private/donation_photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='receipt_photo',
            field=models.ImageField(blank=True, upload_to='private/ngo_receipts/%Y/%m/'),
        ),
    ]
