"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import logging
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-local-development-only-change-me-please")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() in {"1", "true", "yes", "on"}

ALLOWED_HOSTS = [host.strip() for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,testserver").split(",") if host.strip()]

if not DEBUG and (not os.environ.get("DJANGO_SECRET_KEY") or SECRET_KEY.startswith("django-insecure-")):
    raise RuntimeError("DJANGO_SECRET_KEY must be set to a secure value when DJANGO_DEBUG is false.")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "bridge",
    "accounts",
    "donors",
    "donations",
    "volunteers",
    "ngos",
    "payments",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "config.context_processors.map_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("DJANGO_DB_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("DJANGO_DB_NAME", str(BASE_DIR / "db.sqlite3")),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Custom User Model
AUTH_USER_MODEL = "accounts.User"
EMAIL_BACKEND = os.environ.get("DJANGO_EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")

DEFAULT_FROM_EMAIL = os.environ.get("DJANGO_DEFAULT_FROM_EMAIL", "noreply@foodbridge.local")

# Closed demos keep all financial-provider routes disabled unless explicitly enabled.
PAYMENTS_ENABLED = os.environ.get("FOODBRIDGE_PAYMENTS_ENABLED", "false").lower() in {"1", "true", "yes", "on"}

# These are safe for local HTTP development and become mandatory for deployed HTTPS.
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = 31_536_000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"

# Razorpay credentials are deliberately environment-only. Keep the defaults empty so
# payments cannot accidentally be attempted without explicit configuration.
RAZORPAY_MODE = os.environ.get("RAZORPAY_MODE", "test")
RAZORPAY_KEY_ID = os.environ.get("RAZORPAY_KEY_ID", "")
RAZORPAY_KEY_SECRET = os.environ.get("RAZORPAY_KEY_SECRET", "")
RAZORPAY_OAUTH_CLIENT_ID = os.environ.get("RAZORPAY_OAUTH_CLIENT_ID", "")
RAZORPAY_OAUTH_CLIENT_SECRET = os.environ.get("RAZORPAY_OAUTH_CLIENT_SECRET", "")
RAZORPAY_OAUTH_REDIRECT_URI = os.environ.get("RAZORPAY_OAUTH_REDIRECT_URI", "")
RAZORPAY_WEBHOOK_SECRET = os.environ.get("RAZORPAY_WEBHOOK_SECRET", "")
RAZORPAYX_ACCOUNT_NUMBER = os.environ.get("RAZORPAYX_ACCOUNT_NUMBER", "")
PAYMENT_ENCRYPTION_KEY = os.environ.get("PAYMENT_ENCRYPTION_KEY", "")
VOLUNTEER_DELIVERY_FEE_PAISE = int(os.environ.get("VOLUNTEER_DELIVERY_FEE_PAISE", "50000"))

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
GEMINI_VISION_MODEL = os.environ.get("GEMINI_VISION_MODEL", "gemini-2.0-flash")
FOOD_PHOTO_MAX_SIZE_BYTES = int(os.environ.get("FOOD_PHOTO_MAX_SIZE_BYTES", str(5 * 1024 * 1024)))
EVIDENCE_PHOTO_MAX_SIZE_BYTES = int(os.environ.get("EVIDENCE_PHOTO_MAX_SIZE_BYTES", str(5 * 1024 * 1024)))
FOOD_VERIFICATION_TIMEOUT_SECONDS = int(os.environ.get("FOOD_VERIFICATION_TIMEOUT_SECONDS", "15"))
MAP_TILE_URL = os.environ.get("MAP_TILE_URL", "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png")
MAP_TILE_ATTRIBUTION = os.environ.get("MAP_TILE_ATTRIBUTION", "&copy; OpenStreetMap contributors")
GEOCODING_PROVIDER = os.environ.get("GEOCODING_PROVIDER", "photon").lower()
GEOCODING_URL = os.environ.get("GEOCODING_URL", "https://photon.komoot.io/api/")
GEOCODING_USER_AGENT = os.environ.get("GEOCODING_USER_AGENT", "FoodBridge/1.0 contact@example.com")
GEOCODING_TIMEOUT_SECONDS = int(os.environ.get("GEOCODING_TIMEOUT_SECONDS", "5"))
GEOCODING_DEFAULT_COUNTRY = os.environ.get("GEOCODING_DEFAULT_COUNTRY", "India")
GEOCODING_NEARBY_RADIUS_KM = int(os.environ.get("GEOCODING_NEARBY_RADIUS_KM", "500"))
IP_GEOLOCATION_URL = os.environ.get("IP_GEOLOCATION_URL", "https://ipapi.co/{ip}/json/")
IP_GEOLOCATION_TIMEOUT_SECONDS = int(os.environ.get("IP_GEOLOCATION_TIMEOUT_SECONDS", "2"))

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {"structured": {"format": "%(asctime)s %(levelname)s %(name)s %(message)s"}},
    "handlers": {"console": {"class": "logging.StreamHandler", "formatter": "structured"}},
    "root": {"handlers": ["console"], "level": os.environ.get("DJANGO_LOG_LEVEL", "INFO")},
}
